org: jack001
service: ps-detct

custom:
  userPoolId: "us-east-1_ePLUL9Wyz"
  userPoolClientId: "5imlnro24sus4iai99m1379njf"
  userPoolName: "User pool - ps-detect"

stages:
  default:
    params:
      usersTableName: "users-table-${sls:stage}"
      workoutTableName: "workout-table-${sls:stage}"
      s3keyTableName: "s3key-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.userPoolId}
        audience:
          - ${self:custom.userPoolClientId}

  environment:
    USERS_TABLE: ${param:usersTableName}
    WORKOUT_TABLE: ${param:workoutTableName}
    S3KEY_TABLE: ${param:s3keyTableName}
    USER_POOL_ID: ${self:custom.userPoolId}
    USER_POOL_CLIENT_ID: ${self:custom.userPoolClientId}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource: 
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${param:usersTableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${param:workoutTableName}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${param:s3keyTableName}"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
      - httpApi:
          path: /users
          method: POST
          authorizer:
            name: customAuthorizer
      - httpApi:
          path: /users/{userId}
          method: DELETE
          authorizer:
            name: customAuthorizer
      - httpApi:
          path: /users/{userId}
          method: PUT
          authorizer:
            name: customAuthorizer

  userCreated:
    handler: triggers/userCreated.userCreated
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPoolName}
          trigger: PostConfirmation
          existing: true
          forceDeploy: true

  userLoggedIn:
    handler: triggers/userLoggedIn.userLoggedIn
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPoolName}
          trigger: PostAuthentication
          existing: true
          forceDeploy: true


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:usersTableName}

    WorkoutTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: workoutId
            AttributeType: S
        KeySchema:
          - AttributeName: workoutId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:workoutTableName}

    S3KeyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: keyId
            AttributeType: S
        KeySchema:
          - AttributeName: keyId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:s3keyTableName}
