org: jack001
service: ps-detct

custom:
  userPoolId: "us-east-1_ePLUL9Wyz"
  userPoolClientId: "5imlnro24sus4iai99m1379njf"
  poolName: "User pool - ps-detect"

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.userPoolId}
        audience:
          - ${self:custom.userPoolClientId}

  environment:
    USERS_TABLE: ${param:tableName}
    USER_POOL_ID: ${self:custom.userPoolId}
    USER_POOL_CLIENT_ID: ${self:custom.poolName}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${param:tableName}"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
      - httpApi:
          path: /users
          method: POST
          authorizer:
            name: customAuthorizer
      - httpApi:
          path: /users/{userId}
          method: DELETE
          authorizer:
            name: customAuthorizer
      - httpApi:
          path: /users/{userId}
          method: PUT
          authorizer:
            name: customAuthorizer

  userCreated:
    handler: triggers/userCreated.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPoolId}
          trigger: PostConfirmation

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
